title: I'm Pavels, welcome!
description: > # this means to ignore newlines until "baseurl:"
  Scala developer based in Zurich
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pavels Sisojevs # add your name
author-img: me.jpg # add your photo
about-author: Hi, I am a Scala developer based in Zurich, Switzerland. Functional programming explorer, ice hockey enthusiast.
social-github: psisoyev # add your Github handle
social-linkedin: pavels-sisojevs-10601534 # add your Linkedin handle
social-email: p.sisoyev@gmail.com # add your Email address
social-instagram: psisoyev # add your Email address
social-twitter: scalamonster

# Disqus
discus-identifier: psisoyev

# Tracker
analytics: UA-151460957-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-target-blank

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
